# Generated by Django 4.2.1 on 2023-05-21 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAccounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('country_code', models.CharField(max_length=3)),
                ('district', models.CharField(max_length=20)),
                ('population', models.IntegerField()),
            ],
        ),
    ]
