# Generated by Django 4.2.1 on 2023-05-21 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAccounts', '0004_alter_country_capital_alter_country_gnp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countrylanguage',
            name='is_official',
            field=models.CharField(),
        ),
    ]
